export const AppScreen = {
  LANDING: 'LANDING',
  PLANNER: 'PLANNER',
  LOADING: 'LOADING',
  ITINERARY: 'ITINERARY',
  SAMPLE_PLAN: 'SAMPLE_PLAN',
  AUTH: 'AUTH',
  DASHBOARD: 'DASHBOARD',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  SAVED_PLANS: 'SAVED_PLANS',
  ABOUT_US: 'ABOUT_US',
  CONTACT_US: 'CONTACT_US',
};